name: Checkstyle and Tests

on:
  pull_request:
    branches:
      - 'master'
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Checkstyle and Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'temurin'
      - name: Get java-version
        run: |
          BUILD_VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )
          echo "VERSION=$BUILD_VERSION" >> $GITHUB_ENV
      - name: Compile
        run: mvn -X compile
      - name: Checkstyle
        run: mvn -X validate
      - name: Test
        run: mvn -X test
  verify-commits:
    name: Verify Commits
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: Verify Signed-off-by
      run: |
        for commit in $(git rev-list --no-merges HEAD^..HEAD); do
          if ! git log -1 --format=%B "$commit" | grep -q "^Signed-off-by: "; then
            echo "Commit $commit is missing Signed-off-by line."
            exit 1
          fi
        done